export const COTIZACION_CREATE_REQUEST = 'COTIZACION_CREATE_REQUEST';
export const COTIZACION_CREATE_SUCCESS = 'COTIZACION_CREATE_SUCCESS';
export const COTIZACION_CREATE_FAIL = 'COTIZACION_CREATE_FAIL';
export const COTIZACION_CREATE_RESET = 'COTIZACION_CREATE_RESET';

export const COTIZACION_DETAILS_REQUEST = 'COTIZACION_DETAILS_REQUEST';
export const COTIZACION_DETAILS_SUCCESS = 'COTIZACION_DETAILS_SUCCESS';
export const COTIZACION_DETAILS_FAIL = 'COTIZACION_DETAILS_FAIL';

export const COTIZACION_MINE_LIST_REQUEST = 'COTIZACION_MINE_LIST_REQUEST';
export const COTIZACION_MINE_LIST_SUCCESS = 'COTIZACION_MINE_LIST_SUCCESS';
export const COTIZACION_MINE_LIST_FAIL = 'COTIZACION_MINE_LIST_FAIL';

export const COTIZACION_LIST_REQUEST = 'COTIZACION_LIST_REQUEST';
export const COTIZACION_LIST_SUCCESS = 'COTIZACION_LIST_SUCCESS';
export const COTIZACION_LIST_FAIL = 'COTIZACION_LIST_FAIL';

export const COTIZACION_DELETE_REQUEST = 'COTIZACION_DELETE_REQUEST';
export const COTIZACION_DELETE_SUCCESS = 'COTIZACION_DELETE_SUCCESS';
export const COTIZACION_DELETE_FAIL = 'COTIZACION_DELETE_FAIL';
export const COTIZACION_DELETE_RESET = 'COTIZACION_DELETE_RESET';

export const COTIZACION_SUMMARY_REQUEST = 'COTIZACION_SUMMARY_REQUEST';
export const COTIZACION_SUMMARY_SUCCESS = 'COTIZACION_SUMMARY_SUCCESS';
export const COTIZACION_SUMMARY_FAIL = 'COTIZACION_SUMMARY_FAIL';
