export const ENTRADA_CREATE_REQUEST = 'ENTRADA_CREATE_REQUEST';
export const ENTRADA_CREATE_SUCCESS = 'ENTRADA_CREATE_SUCCESS';
export const ENTRADA_CREATE_FAIL = 'ENTRADA_CREATE_FAIL';
export const ENTRADA_CREATE_RESET = 'ENTRADA_CREATE_RESET';

export const ENTRADA_PAY_REQUEST = 'ENTRADA_PAY_REQUEST';
export const ENTRADA_PAY_SUCCESS = 'ENTRADA_PAY_SUCCESS';
export const ENTRADA_PAY_FAIL = 'ENTRADA_PAY_FAIL';
export const ENTRADA_PAY_RESET = 'ENTRADA_PAY_RESET';

export const ENTRADA_DELIVER_REQUEST = 'ENTRADA_DELIVER_REQUEST';
export const ENTRADA_DELIVER_SUCCESS = 'ENTRADA_DELIVER_SUCCESS';
export const ENTRADA_DELIVER_FAIL = 'ENTRADA_DELIVER_FAIL';
export const ENTRADA_DELIVER_RESET = 'ENTRADA_DELIVER_RESET';

export const ENTRADA_DETAILS_REQUEST = 'ENTRADA_DETAILS_REQUEST';
export const ENTRADA_DETAILS_SUCCESS = 'ENTRADA_DETAILS_SUCCESS';
export const ENTRADA_DETAILS_FAIL = 'ENTRADA_DETAILS_FAIL';

export const ENTRADA_MINE_LIST_REQUEST = 'ENTRADA_MINE_LIST_REQUEST';
export const ENTRADA_MINE_LIST_SUCCESS = 'ENTRADA_MINE_LIST_SUCCESS';
export const ENTRADA_MINE_LIST_FAIL = 'ENTRADA_MINE_LIST_FAIL';

export const ENTRADA_LIST_REQUEST = 'ENTRADA_LIST_REQUEST';
export const ENTRADA_LIST_SUCCESS = 'ENTRADA_LIST_SUCCESS';
export const ENTRADA_LIST_FAIL = 'ENTRADA_LIST_FAIL';

export const ENTRADA_DELETE_REQUEST = 'ENTRADA_DELETE_REQUEST';
export const ENTRADA_DELETE_SUCCESS = 'ENTRADA_DELETE_SUCCESS';
export const ENTRADA_DELETE_FAIL = 'ENTRADA_DELETE_FAIL';
export const ENTRADA_DELETE_RESET = 'ENTRADA_DELETE_RESET';

export const ENTRADA_SUMMARY_REQUEST = 'ENTRADA_SUMMARY_REQUEST';
export const ENTRADA_SUMMARY_SUCCESS = 'ENTRADA_SUMMARY_SUCCESS';
export const ENTRADA_SUMMARY_FAIL = 'ENTRADA_SUMMARY_FAIL';

export const ENTRADA_PAYCONFIRM_REQUEST = 'ENTRADA_PAYCONFIRM_REQUEST';
export const ENTRADA_PAYCONFIRM_SUCCESS = 'ENTRADA_PAYCONFIRM_SUCCESS';
export const ENTRADA_PAYCONFIRM_FAIL = 'ENTRADA_PAYCONFIRM_FAIL';
export const ENTRADA_PAYCONFIRM_RESET = 'ENTRADA_PAYCONFIRM_RESET';
