export const PROVEEDOR_REGISTER_REQUEST = 'PROVEEDOR_REGISTER_REQUEST';
export const PROVEEDOR_REGISTER_SUCCESS = 'PROVEEDOR_REGISTER_SUCCESS';
export const PROVEEDOR_REGISTER_FAIL = 'PROVEEDOR_REGISTER_FAIL';
export const PROVEEDOR_REGISTER_RESET = 'PROVEEDOR_REGISTER_RESET';

export const PROVEEDOR_SIGNIN_REQUEST = 'PROVEEDOR_SIGNIN_REQUEST';
export const PROVEEDOR_SIGNIN_SUCCESS = 'PROVEEDOR_SIGNIN_SUCCESS';
export const PROVEEDOR_SIGNIN_FAIL = 'PROVEEDOR_SIGNIN_FAIL';

export const PROVEEDOR_SIGNOUT = 'PROVEEDOR_SIGNOUT';

export const PROVEEDOR_DETAILS_REQUEST = 'PROVEEDOR_DETAILS_REQUEST';
export const PROVEEDOR_DETAILS_SUCCESS = 'PROVEEDOR_DETAILS_SUCCESS';
export const PROVEEDOR_DETAILS_FAIL = 'PROVEEDOR_DETAILS_FAIL';
export const PROVEEDOR_DETAILS_RESET = 'PROVEEDOR_DETAILS_RESET';

export const PROVEEDOR_LIST_REQUEST = 'PROVEEDOR_LIST_REQUEST';
export const PROVEEDOR_LIST_SUCCESS = 'PROVEEDOR_LIST_SUCCESS';
export const PROVEEDOR_LIST_FAIL = 'PROVEEDOR_LIST_FAIL';
export const PROVEEDOR_LIST_RESET = 'PROVEEDOR_LIST_RESET';

export const PROVEEDOR_TOPSELLERS_LIST_REQUEST = 'PROVEEDOR_TOPSELLERS_LIST_REQUEST';
export const PROVEEDOR_TOPSELLERS_LIST_SUCCESS = 'PROVEEDOR_TOPSELLERS_LIST_SUCCESS';
export const PROVEEDOR_TOPSELLERS_LIST_FAIL = 'PROVEEDOR_TOPSELLERS_LIST_FAIL';

export const PROVEEDOR_UPDATE_PROFILE_REQUEST = 'PROVEEDOR_UPDATE_PROFILE_REQUEST';
export const PROVEEDOR_UPDATE_PROFILE_SUCCESS = 'PROVEEDOR_UPDATE_PROFILE_SUCCESS';
export const PROVEEDOR_UPDATE_PROFILE_FAIL = 'PROVEEDOR_UPDATE_PROFILE_FAIL';
export const PROVEEDOR_UPDATE_PROFILE_RESET = 'PROVEEDOR_UPDATE_PROFILE_RESET';

export const PROVEEDOR_UPDATE_REQUEST = 'PROVEEDOR_UPDATE_REQUEST';
export const PROVEEDOR_UPDATE_SUCCESS = 'PROVEEDOR_UPDATE_SUCCESS';
export const PROVEEDOR_UPDATE_FAIL = 'PROVEEDOR_UPDATE_FAIL';
export const PROVEEDOR_UPDATE_RESET = 'PROVEEDOR_UPDATE_RESET';

export const PROVEEDOR_DELETE_REQUEST = 'PROVEEDOR_DELETE_REQUEST';
export const PROVEEDOR_DELETE_SUCCESS = 'PROVEEDOR_DELETE_SUCCESS';
export const PROVEEDOR_DELETE_FAIL = 'PROVEEDOR_DELETE_FAIL';
export const PROVEEDOR_DELETE_RESET = 'PROVEEDOR_DELETE_RESET';

export const PROVEEDOR_ADDRESS_MAP_CONFIRM = 'PROVEEDOR_ADDRESS_MAP_CONFIRM';
