export const REGISTRO_LIST_REQUEST = 'REGISTRO_LIST_REQUEST';
export const REGISTRO_LIST_SUCCESS = 'REGISTRO_LIST_SUCCESS';
export const REGISTRO_LIST_FAIL = 'REGISTRO_LIST_FAIL';

export const REGISTRO_DETAILS_REQUEST = 'REGISTRO_DETAILS_REQUEST';
export const REGISTRO_DETAILS_SUCCESS = 'REGISTRO_DETAILS_SUCCESS';
export const REGISTRO_DETAILS_FAIL = 'REGISTRO_DETAILS_FAIL';

export const REGISTRO_CREATE_REQUEST = 'REGISTRO_CREATE_REQUEST';
export const REGISTRO_CREATE_SUCCESS = 'REGISTRO_CREATE_SUCCESS';
export const REGISTRO_CREATE_FAIL = 'REGISTRO_CREATE_FAIL';
export const REGISTRO_CREATE_RESET = 'REGISTRO_CREATE_RESET';

export const REGISTRO_UPDATE_REQUEST = 'REGISTRO_UPDATE_REQUEST';
export const REGISTRO_UPDATE_SUCCESS = 'REGISTRO_UPDATE_SUCCESS';
export const REGISTRO_UPDATE_FAIL = 'REGISTRO_UPDATE_FAIL';
export const REGISTRO_UPDATE_RESET = 'REGISTRO_UPDATE_RESET';

export const REGISTRO_DELETE_REQUEST = 'REGISTRO_DELETE_REQUEST';
export const REGISTRO_DELETE_SUCCESS = 'REGISTRO_DELETE_SUCCESS';
export const REGISTRO_DELETE_FAIL = 'REGISTRO_DELETE_FAIL';
export const REGISTRO_DELETE_RESET = 'REGISTRO_DELETE_RESET';

export const REGISTRO_CATEGORY_LIST_REQUEST = 'REGISTRO_CATEGORY_LIST_REQUEST';
export const REGISTRO_CATEGORY_LIST_SUCCESS = 'REGISTRO_CATEGORY_LIST_SUCCESS';
export const REGISTRO_CATEGORY_LIST_FAIL = 'REGISTRO_CATEGORY_LIST_FAIL';

export const REGISTRO_BYCODE_REQUEST = 'REGISTRO_BYCODE_REQUEST';
export const REGISTRO_BYCODE_SUCCESS = 'REGISTRO_BYCODE_SUCCESS';
export const REGISTRO_BYCODE_FAIL = 'REGISTRO_BYCODE_FAIL';
export const REGISTRO_BYCODE_RESET = 'REGISTRO_BYCODE_RESET';
