export const tipoop = [' ', 'Pago', 'Ingreso'];
export const selectTipoDoc = [
	' ',
	'Factura',
	'Recibo',
	'Nota Debito',
	'Nota Credito',
	'Nota Entrega',
	'Nota Almacen',
];

export const marcas = [
	' ',
	'Aci',
	'Airtex',
	'Aksu',
	'Amelie',
	'Atp',
	'Ayd',
	'Bando',
	'Bosch',
	'Champions',
	'Cns',
	'Coni-Seal',
	'Crc',
	'Crown',
	'Dana',
	'Dayco',
	'Delphi',
	'Denso',
	'Depo',
	'Detroit Axle',
	'Dorman',
	'Driveshasft Parts',
	'Duncan',
	'Eccp',
	'Febest',
	'Felpro',
	'Gabriel',
	'Generico',
	'Global Uac',
	'Gmg',
	'Hayden',
	'Hercko',
	'Inyecto Motriz',
	'Johnsens',
	'Leoni',
	'Locitte',
	'Lucas',
	'Magneti Marelli',
	'Mahle',
	'Melling',
	'Mevotech',
	'Mobil',
	'Moog',
	'Mopar',
	'Motor Medic',
	'Motorad',
	'Motorcraft',
	'Ngk',
	'Ome',
	'Omix',
	'Procomp',
	'Proshock',
	'Safextop',
	'Skp',
	'Speed Motor',
	'Sq',
	'Stabilus',
	'Standard',
	'Standard ',
	'Stant',
	'Strongarm',
	'Sunbelt',
	'Supers',
	'Sylvania',
	'Tekstar',
	'Thomson',
	'Timken',
	'Titanium',
	'Trenden',
	'Trenden ',
	'Trs',
	'Tyc',
	'Uac',
	'Ultra Power',
	'Wagner',
	'Waypro',
	'Westar',
	'Winner',
	'Wix',
	'Yukkaso',
];

export const opciones = [
	{ value: 'JT', label: 'JT' },
	{ value: 'JL', label: 'JL' },
	{ value: 'JK', label: 'JK' },
	{ value: 'TJ', label: 'TJ' },
	{ value: 'YJ', label: 'YJ' },
	{ value: 'KL', label: 'KL' },
	{ value: 'XJ', label: 'XJ' },
	{ value: 'MJ', label: 'MJ' },
	{ value: 'WK2', label: 'WK2' },
	{ value: 'WK', label: 'WK' },
	{ value: 'WJ', label: 'WJ' },
	{ value: 'ZJ', label: 'ZJ' },
	{ value: 'XK', label: 'XK' },
	{ value: 'KK', label: 'KK' },
	{ value: 'KJ', label: 'KJ' },
	{ value: 'MP', label: 'MP' },
	{ value: 'MK', label: 'MK' },
	{ value: 'BV', label: 'BV' },
	{ value: 'BU', label: 'BU' },
	{ value: 'PM', label: 'PM' },
	{ value: 'PL', label: 'PL' },
	{ value: 'PL2', label: 'PL2' },
	{ value: 'DH', label: 'DH' },
	{ value: 'DM', label: 'DM' },
	{ value: 'DS', label: 'DS' },
	{ value: 'ND', label: 'ND' },
	{ value: 'PT', label: 'PT' },
	{ value: 'RG', label: 'RG' },
];

export const selectYears = [
	{ value: '1984', label: '1984' },
	{ value: '1985', label: '1985' },
	{ value: '1986', label: '1986' },
	{ value: '1987', label: '1987' },
	{ value: '1988', label: '1988' },
	{ value: '1989', label: '1989' },
	{ value: '1990', label: '1990' },
	{ value: '1991', label: '1991' },
	{ value: '1992', label: '1992' },
	{ value: '1993', label: '1993' },
	{ value: '1994', label: '1994' },
	{ value: '1995', label: '1995' },
	{ value: '1996', label: '1996' },
	{ value: '1997', label: '1997' },
	{ value: '1998', label: '1998' },
	{ value: '1999', label: '1999' },
	{ value: '2000', label: '2000' },
	{ value: '2001', label: '2001' },
	{ value: '2002', label: '2002' },
	{ value: '2003', label: '2003' },
	{ value: '2004', label: '2004' },
	{ value: '2005', label: '2005' },
	{ value: '2006', label: '2006' },
	{ value: '2007', label: '2007' },
	{ value: '2008', label: '2008' },
	{ value: '2009', label: '2009' },
	{ value: '2010', label: '2010' },
	{ value: '2011', label: '2011' },
	{ value: '2012', label: '2012' },
	{ value: '2013', label: '2013' },
	{ value: '2014', label: '2014' },
	{ value: '2015', label: '2015' },
	{ value: '2016', label: '2016' },
	{ value: '2017', label: '2017' },
	{ value: '2018', label: '2018' },
	{ value: '2019', label: '2019' },
	{ value: '2020', label: '2020' },
	{ value: '2021', label: '2021' },
	{ value: '2022', label: '2022' },
];

export const selectMotores = [
	{ value: '4.0L', label: '4.0L' },
	{ value: '2.5L', label: '2.5L' },
	{ value: '2.0L', label: '2.0L' },
	{ value: '5.2L', label: '5.2L' },
	{ value: '3.7L', label: '3.7L' },
	{ value: '2.4L', label: '2.4L' },
	{ value: '3.3L', label: '3.3L' },
	{ value: '4.7L', label: '4.7L' },
	{ value: '5.7L', label: '5.7L' },
	{ value: '3.6L', label: '3.6L' },
	{ value: '1.8L', label: '1.8L' },
	{ value: '5.9L', label: '5.9L' },
	{ value: '3.8L', label: '3.8L' },
	{ value: '6.4L', label: '6.4L' },
];

export const selectModelos = [
	{ value: 'COMANCHE', label: 'COMANCHE' },
	{ value: 'WRANGLER', label: 'WRANGLER' },
	{ value: 'GRAND CHEROKEE', label: 'GRAND CHEROKEE' },
	{ value: 'NEON', label: 'NEON' },
	{ value: 'CHEROKEE', label: 'CHEROKEE' },
	{ value: 'RAM', label: 'RAM' },
	{ value: 'LIBERTY KJ', label: 'LIBERTY KJ' },
	{ value: 'PT CRUISER', label: 'PT CRUISER' },
	{ value: 'CARAVAN TOWN COUNTRY', label: 'CARAVAN TOWN COUNTRY' },
	{ value: 'COMMANDER', label: 'COMMANDER' },
	{ value: 'DAKOTA', label: 'DAKOTA' },
	{ value: 'CALIBER', label: 'CALIBER' },
	{ value: 'LIBERTY KK', label: 'LIBERTY KK' },
	{ value: 'COMPASS', label: 'COMPASS' },
	{ value: 'RENEGADE', label: 'RENEGADE' },
	{ value: 'GLADIATOR', label: 'GLADIATOR' },
];

export const selectVehiculos = [
	{ value: 'JEEP', label: 'JEEP' },
	{ value: 'DODGE', label: 'DODGE' },
	{ value: 'CHRYSLER', label: 'CHRYSLER' },
];

export const presentaciones = ['unidad', 'caja', 'bulto', 'docena', 'paquete'];

export const customStyles = {
	option: (provided, state) => ({
		...provided,
		borderBottom: '1px dotted pink',
		color: state.isSelected ? 'red' : 'blue',
		padding: 20,
		width: 250,
	}),
};
