export const SETTINGS_REGISTER_REQUEST = 'SETTINGS_REGISTER_REQUEST';
export const SETTINGS_REGISTER_SUCCESS = 'SETTINGS_REGISTER_SUCCESS';
export const SETTINGS_REGISTER_FAIL = 'SETTINGS_REGISTER_FAIL';
export const SETTINGS_REGISTER_RESET = 'SETTINGS_REGISTER_RESET';

export const SETTINGS_DETAILS_REQUEST = 'SETTINGS_DETAILS_REQUEST';
export const SETTINGS_DETAILS_SUCCESS = 'SETTINGS_DETAILS_SUCCESS';
export const SETTINGS_DETAILS_FAIL = 'SETTINGS_DETAILS_FAIL';
export const SETTINGS_DETAILS_RESET = 'SETTINGS_DETAILS_RESET';

export const SETTINGS_LIST_REQUEST = 'SETTINGS_LIST_REQUEST';
export const SETTINGS_LIST_SUCCESS = 'SETTINGS_LIST_SUCCESS';
export const SETTINGS_LIST_FAIL = 'SETTINGS_LIST_FAIL';
export const SETTINGS_LIST_RESET = 'SETTINGS_LIST_RESET';

export const SETTINGS_UPDATE_REQUEST = 'SETTINGS_UPDATE_REQUEST';
export const SETTINGS_UPDATE_SUCCESS = 'SETTINGS_UPDATE_SUCCESS';
export const SETTINGS_UPDATE_FAIL = 'SETTINGS_UPDATE_FAIL';
export const SETTINGS_UPDATE_RESET = 'SETTINGS_UPDATE_RESET';
